export interface Lead{
    leadId:number,
    firstName:string,
    lastName: string,
    email: string,
    leadStatus: number,
    companyId: number,
    saleOwner: number,
    assignedTo: number,
    mobile: string,
    work:string,
    address: string,
    street:string,
    city:string,
    zip: string,
    state: string,
    country:string,
    leadSourceId: string,
    leadIndustryId: string,
    createdDate: Date,
}